spring:
  application:
    name: dashboard
  datasource:
    username: postgres
    password: 7777
    url: jdbc:postgresql://localhost:5432/dashboard
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true


jwt:
  lifetime: 24h
  secret: a7b49f2c628facf950bffe6f734ec3158c9eebc40d2c68089ca3505ce8cde38c